### ISSUE TITLE
no need the bind.go ? 

### ISSUE THREAD

**Issue by BeanWei** [ZEROKISEKI/starsManager#3]
为什么您这里面没有bind.go这个文件呀，Asset这个没有看到定义呀？

**Comment by ZEROKISEKI** [comment]
因为go-astilectron-bundler命令生成了对应系统下的bind.go文件(比如在mac是生成了bind-darwin-amd64.go)，Asset是对应生成的bind.go定义的

**Comment by BeanWei** [comment]
的确是这样。还麻烦请教你下，开发过程中如何进行debug了，必须打包成exe吗？您有更好的方法吗？
我用go run *.go 会报一堆 的错误，不知道为啥

**Comment by ZEROKISEKI** [comment]
可能你是windows系统，windows系统cmd不支持*通配的形式, 你可以用go build或者`go run main.go message.go ....`的命令去跑

**Comment by ZEROKISEKI** [comment]
目前这个项目由于原作者将go-astilectron-bundler和go-astilectron做了一定的修改，所以可能会跑不起来。。。有时间会做下更新

**Comment by BeanWei** [comment]
感谢您的回复，看来得自己继续爬坑了。

**Comment by BeanWei** [comment]
请问您，我不用vuex，
在main.js 中：
document.addEventListener('astilectron-ready', function() {}

组件中：
login() {
      astilectron.sendMessage({ name: "Login" ，payload:"test"}, function (message) {})
    }

go中接收payload:
func handleMessages(a *astilectron.Astilectron, _ *astilectron.Window, m bootstrap.MessageIn) (payload interface{}, err error) {
	switch m.Name {
	case "Login":
		{
			var a string

			err := json.Unmarshal(m.Payload, &a)
			if err != nil {
				return err.Error(), nil
			}
			astilog.Debug(a)
		}
	}
	return
}
为什么debug模式下 go没有任何输出呀？
